export const API_URL = "http://localhost:8081"
export const AUTH_URL = "/api/security/user/me"
export const LOGIN_URL = "/api/security/login"
export const UPDATE_URL = "/api/security/user/update"
export const DELETE_URL = "/api/security/user/delete"
export const GET_URL = "/api/security/user/"
export const SAVE_URL = "/api/security/user/save"